export const PAST_ORGANIZATIONS = [
  { name: "Google DeepMind", logo: "/images/orgs/google-deepmind.png", url: "https://deepmind.google" },
  { name: "Probabl", logo: "/images/orgs/probabl.png", url: "https://probabl.ai" },
  { name: "ZhipuAI", logo: "/images/orgs/zhipuai.png", url: "https://zhipuai.cn" },
  { name: "Moonshot AI", logo: "/images/orgs/moonshot-ai.png", url: "https://moonshot.cn" },
  { name: "Minimax", logo: "/images/orgs/minimax.png", url: "https://minimaxi.com" },
  { name: "BAAI", logo: "/images/orgs/baai.png", url: "https://baai.ac.cn" },
  { name: "CSDN", logo: "/images/orgs/csdn.png", url: "https://csdn.net" },
  { name: "LF AI & Data", logo: "/images/orgs/lf-ai-data.svg", url: "https://lfaidata.foundation" },
  { name: "Rust Foundation", logo: "/images/orgs/rust-foundation.png", url: "https://rustfoundation.org" },
  { name: "Kaiyuanshe", logo: "/images/orgs/kaiyuanshe.svg", url: "https://kaiyuanshe.cn" },
  { name: "CNRS", logo: "/images/orgs/cnrs.png", url: "https://cnrs.fr" },
  { name: "Fudan University", logo: "/images/orgs/fudan.svg", url: "https://fudan.edu.cn" },
  { name: "Tulane University", logo: "/images/orgs/tulane.png", url: "https://tulane.edu" },
  { name: "McGill University", logo: "/images/orgs/mcgill.png", url: "https://mcgill.ca" },
  { name: "BNBU", logo: "/images/orgs/bnbu.png", url: "https://bnbu.edu.cn" },
  { name: "SOLEIL Synchrotron", logo: "/images/orgs/soleil.png", url: "https://www.synchrotron-soleil.fr/en" },
  { name: "United Nations University", logo: "/images/orgs/unu.png", url: "https://unu.edu" },
  { name: "Chinese Academy of Social Sciences", logo: "/images/orgs/cass.png", url: "https://cssn.cn" },
  { name: "China Electronics Standardization Institute", logo: "/images/orgs/cesi.png", url: "https://csa-iot.org/member/china-electronics-standardization-institute/" },
  { name: "Egen AI", logo: "/images/orgs/egen.png", url: "https://egen.ai" },
  { name: "Advanced AI Society", logo: "/images/orgs/advanced-ai-society.svg", url: "https://advancedaisociety.org" },
  { name: "Alma AI", logo: "/images/orgs/alma-ai.png", url: "https://centri.unibo.it/alma-ai" },
  { name: "University of Bologna", logo: "/images/orgs/university-of-bologna.png", url: "https://www.unibo.it/en" },
  { name: "Voice Interoperability", logo: "/images/orgs/voice-interoperability.svg", url: "https://voiceinteroperability.ai" },
  { name: "Institute for Technoscience and Society", logo: "/images/orgs/technoscience-society.png", url: "https://www.yorku.ca/research/its/" },
] as const;
